import { Inter } from "next/font/google";
import "@/app/globals.css";
import SideNav from "@/app/ui/dashboard/sidenav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "React Practice",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          <div className="w-full flex-none md:w-64">
            <SideNav />
          </div>
          <div className="flex-grow p-6 md:overflow-y-auto md:p-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
